Added commit created squash with message

diff --git a/git-squash b/git-squash
--- a/git-squash
+++ b/git-squash
@@ -4,52 +4,78 @@ usage() {
 	git squash --help
 }
 main(){
-	if [ "$#" -lt 1 ]; then
+	if [[ "$#" -lt 1 ]]; then
 		usage; exit 1
 	fi
+
+	if [[ "$@" =~ (-h|--help) ]]; then
+		usage; 
+		exit 0
+	fi
 	
-	local subcomand=$1; shift
+	while [[ "$#" > 0 ]]; do
 
-	case $subcomand in
-		"-h"|"--help")
-			usage; exit 0
-			;;
-		"-c"|"--commit")
-			squash_by_commit "$@";
-			;;
-		"-d"|"--diff")
-			squash_by_diff "$@";
-			;;
-		*)
-			usage; exit 1
-			;;
+		local key=$1; shift		
+		local value=$1; shift
 
-	esac
+		if [[ -z $value ]]; then
+			echo "value for $key required, see git squash --help"
+			exit 1
+			break
+		fi
+
+		case $key in
+			"-c"|"--commit")				
+				local commit_id=$value
+				;;
+			"-d"|"--diff")
+				local branch=$value
+				;;
+			"-m"|"--message")
+				local message=$value
+				;;
+			*)
+				echo "Invalid argument $key, see git squash --help."
+				echo
+				exit 1
+				;;
+
+		esac
+	done
+	
+	if [[ $commit_id && $branch ]]; then
+		echo "use only one of either '--diff' or '--commit'"
+		exit 1
+	fi
+
+	if [[ -z "$message" ]]; then
+		echo "Message required, see git squash --help"
+		exit 1
+	fi
+
+	if [[ $commit_id ]]; then
+		squash_by_commit $commit_id $message
+	else
+		squash_by_diff $branch $message
+	fi 
+		
 }
 
 squash_by_commit() {
-	if [ "$#" -lt 1 ]; then
-		echo "Missing argument <commit>"
-		echo
-		usage; exit 1
-	fi
-
-	local commit_expression="$1"
+	local commit_expression="$1"; shift
+	local message=$@
 
 	git reset --soft $commit_expression
+	git commit -a -m "$message"
 
 	exit 0
 }
 
 squash_by_diff() {
-	if [ "$#" -lt 1 ]; then
-		echo "Missing argument <target-branch>"
-		echo
-		usage; exit 1
-	fi
-
 	local source_branch="HEAD"
-	local target_branch="$1"
+	local target_branch="$1"; shift
+	local message=$@
+
 	local timestamp=$(date +%s)
 	
 	local source_commits_file=$(echo "${TMPDIR}${timestamp}_${source_branch}.log")
@@ -61,6 +87,7 @@ squash_by_diff() {
 	local total_of_commits="$(diff $source_commits_file $target_commits_file | grep "<" | sed -n \$=)"
 
 	git reset --soft HEAD~$total_of_commits
+	git commit -a -m "$message"
 
 	exit 0
 }
